### PR TITLE
Add pre-commit

### PR DESCRIPTION
**Pull request by kallewesterling**
Adding in pre-commit + GitHub action. I haven't been able to properly test the GitHub action (because I don't know how to do that!) but I've used [the YAML that Aoife wrote for the AssurancePlatform project](https://github.com/alan-turing-institute/AssurancePlatform/blob/main/.github/workflows/ci.yaml) here and it's working there with a similar config.

### CODE REVIEW

**Comment by kallewesterling** [comment]
You'll see that the precommit action fails above -- that's expected and can be resolved by running

```
$ pre-commit run --all-files
```

and then committing all the imports.

**Comment by mastoffel** [comment]
Great work @kallewesterling ! Works really well for me. 
Is there anything speaking against running `pre-commit run --all-files` and submitting the re-ordered imports with this PR?

**Comment by kallewesterling** [comment]
No, I can do that! Just didn't want there to be too many conflicts, but let's try and see!

**Comment by kallewesterling** [comment]
Would you be able to resolve the conflicts, as you're more familiar with the imports. It looks like `scorch` is the culprit most of the time.

**Comment by mastoffel** [comment]
yes, I'll check that

**Comment by mastoffel** [comment]
ok, that should be it! Feel free to merge @kallewesterling !

**Pull request merged**
