### PR TITLE
Resolve red background on notebook outputs in documentation

### LINKED ISSUE #151: Resolve red background on notebook outputs in documentation

### PR DESCRIPTION
**Pull request by kallewesterling**
Fixes #151

### CODE REVIEW

**Comment by mastoffel** [comment]
@kallewesterling could you give a bit of detail here? When do you see a red background on notebook outputs? Is `ch = logging.StreamHandler(sys.stdout)` the fix?

**Comment by kallewesterling** [comment]
Yes, sorry! So when the example notebook below (in the image) would render the outputs, they would look like warnings, but a quick googling showed that this solves it. It's a quirk with JupyterBook I think.

image

**Comment by kallewesterling** [comment]
@mastoffel would you be able to approve this before our demo meeting, you think?

**Comment by mastoffel** [comment]
@kallewesterling yes of course, sorry! Happy to merge.

**Pull request merged**
