### PR TITLE
Create one tutorial/example notebook

### PR DESCRIPTION
**Pull request by kallewesterling**
I am creating a draft PR here so it's easier to have a conversation about what this looks like.

### CODE REVIEW

**Comment by mastoffel** [comment]
Also just to summarise:
1) Modified quickstart 
2) Added Tutorial
3) Slightly changed save_model() method to take a model instead of saving the best model

**Comment by kallewesterling** [comment]
@mastoffel Should we open this as a real PR?

**Comment by mastoffel** [comment]
@kallewesterling yes, I think so. I'm currently working on another PR which will change the tutorials slightly, so will do that first and then give the tutorials an overhaul.

**Comment by mastoffel** [comment]
A few more changes, mainly:
* worked on quickstart.ipynb
* worked on 01_start.ipynb (more in depth tutorial)
 @kallewesterling @bryanlimy any comments on those two tutorials would be appreciated!

There are a few more changes in here (which should have probably been in another PR), but nothing big.

**Comment by kallewesterling** [comment]
Thanks @mastoffel -- I'll try to have a look at this today so we can get this PR approved before the end of the sprint!

**Comment by mastoffel** [comment]
@kallewesterling did you have a chance to look at the tutorials? If not, I think it should be ok to merge. They'll get a re-write anyway soon.

**Review by mastoffel — APPROVED** [review]

**Pull request merged**
